### PR TITLE
Bump k8s to v1.26

### PR DESCRIPTION
**Pull request by inFocus7**
Using the new base branch `gloo-repo-branch` based off of our `gloo-edge-safe-hasher` tag. *ONLY* (as far as i know) to be used for import in Gloo OSS.

- bumps k8s dependencies to 1.26
- bump go to 1.19 for parity with our other repos. it split require blocks into two - direct and indirect deps - as expected on go 1.17(?)+
- bumps skv2 + solo-kit
- updates gh actions to use newer runners (they didn't run beforehand), and use the `go.mod` go version

Note: skv2 went from 0.17 => 0.30, could this lead to issues? is it worth backporting the skv2 k8s upgrade to 0.17? 
    - From bringing this dependency into my gloo PR, there are no apparent issues so this seems relatively safe.

### CODE REVIEW

**Comment by inFocus7** [comment]
undrafting, just to make sure CI runs and i can see if anything breaks/broke

**Comment by inFocus7** [comment]
CI never ran, pushing empty commit. Want to make sure this is okay to bump skv2 and bringing it in gloo doesn't break anything

**Comment by inFocus7** [comment]
CI not running. maybe due to old gh runner version? I see `main` does not have any github workflows, so I'm going to just bring this into my gloo branch and see if it works..

**Comment by inFocus7** [comment]
woo they ran and passed 🥳

**Review by sam-heilbron — APPROVED** [review]

**Pull request merged**
